name = "blog-fetcher"
main = "../workers/blog-fetcher.ts"
compatibility_date = "2025-04-04"

# Workers AI設定
compatibility_flags = []

# ログと可観測性の設定
usage_model = "bundled"
workers_dev = true
logpush = false
observability = { enabled = true }

# ルート設定
routes = []

# 開発環境設定
[dev]
ip = "localhost"
port = 8787
local_protocol = "http"
upstream_protocol = "https" 