// Generated by Wrangler
// After adding bindings to `wrangler.jsonc`, regenerate this interface via `npm run cf-typegen`
declare namespace Cloudflare {
	interface Env {
		"about-lamaglama39-blog-cache": KVNamespace;
	}
}
interface Env extends Cloudflare.Env {}
